name: Publish Package to npm
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: cp README.md packages/teora-react-arborist/README.md
      - run: yarn
      - run: yarn workspace teora-react-arborist build
      - run: yarn workspace teora-react-arborist npm publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
